# Modelization of a social Network

## I Community representation


### 1) Packages

In [27]:
import scipy.optimize as opt
import numpy as np
from math import *
import matplotlib.pyplot as plt
from DataSet import generateDataSet

### 2) Definition of the posterior

After Computation we obtain the following posterior:

In [57]:

## Compute the lambdas
def strength(i,j,p,vec):
    summ = 0
    for l in range(p):
        summ += vec[i,l]*vec[j,l]
    return summ

# n : Population / p : Number of communities / k : Number of ranks / a,b : Gamma parameters / w = Community parameter
#/ rho : Data rho[i,j] jth selection of the ith person
def posterior(n,p,k,a,b,w,rho):
    vec = w.reshape((n,p))
    summa = 0
    for i in range(n):
        for u in range(p):
            summa += (a-1)*log(abs(vec[i,u]) + 0.000000000000001) - b*vec[i,u]
        totalStrength = 0
        listIndex = [l for l in range(n)]
        del listIndex[i]
        for u in (listIndex):
            totalStrength += strength(i,u,p,vec)
        stateStrength = 0
        for j in range(k):
            totalStrength -= stateStrength
            summa -= log(abs(totalStrength) + 0.000000000000001)
            stateStrength = strength(i,rho[i,j],p,vec)
            summa += log(abs(stateStrength) + 0.000000000000001)
    #print("Flag Optimization", summa)
    return summa

### 3) Optimization

In [60]:
def optimize(n,p ,k,a,b,rho,w0):
    costFunction = lambda w : (-1)*posterior(n,p,k,a,b,w,rho)
    #w0 = (1/p)*np.ones(n*p) ## Initialization
    consMat = [[1 for i in range(p)] + [0 for i in range((n-1)*p)]] + [([0 for i in range(j*p)] + [1 for i in range(p)] + [0 for i in range((n-j-1)*p)]) for j in range(1,n-1)] + [[0 for i in range((n-1)*p)] + [1 for i in range(p)]]
    A = np.concatenate((np.eye(n*p), np.array(consMat)), axis=0)
    lowb = np.array([0 for i in range(n*p)] + [1 for i in range(n)])
    uppb = np.array([1 for i in range(n*(p+1))])
    return opt.minimize(costFunction,w0,bounds = [(0,1) for i in range(n*p)])

## II Test

### 1) Data Generation

##### Random Generation

In [5]:
n = 40
p = 3
k = 4
a = 1
b = 1
def generateRank(n,k):
    sol = [np.random.choice([j for j in range(i-1)] + [j for j in range(i,n)], k, replace = False) for i in range(n)]
    return np.array(sol)
rho = generateRank(n,k)

##### Sampson's Data Set

In [55]:
## Convert the array from the Sampson's DataSet in the format of the data in the dissertation Proposal
def dataProcessing(arr,k):
    r,s = arr.shape
    sol = np.zeros((r,k),dtype = 'int')
    for i in range(r):
        for j in range(1,k+1):
            for l in range(s):
                if arr[i,l] == j:
                    sol[i,j-1] = int(l)
    return sol

In [56]:
listData = generateDataSet()
arr = listData[0]
n,p = arr.shape
k = 3
p = 3
a = 1
b = 1
rho = dataProcessing(arr,k)

### 2) Posterior Minimization

In [59]:
w0 =  np.random.rand(n*p)
result = optimize(n,p ,k,a,b,rho,w0)
minimum, xminimum = result.fun, result.x
for i in range(200):
    w0 =  np.random.rand(n*p)
    result = optimize(n,p ,k,a,b,rho,w0)
    if result.fun < minimum:
        minimum, xminimum = result.fun, result.x
        print(minimum)
print(minimum, xminimum)

(72, 54)
(72, 54)
105.9288105974957
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(72, 54)
(

### Result Processing

In [62]:
x = xminimum.reshape((n,p))
print(x)
posterior(n,p,k,a,b,x,rho)

[[0.23577325 0.15362507 0.43325226]
 [0.18777684 0.03475494 0.47361819]
 [0.         0.         0.19218582]
 [0.         0.29223243 0.        ]
 [0.         0.52536869 0.        ]
 [0.         0.09493313 0.        ]
 [0.         0.         0.49863104]
 [0.00736319 0.31239259 0.26719613]
 [0.         0.27002699 0.03013123]
 [0.03654168 0.15007752 0.        ]
 [0.12233403 0.21324409 0.        ]
 [0.         0.         0.        ]
 [0.         0.09168993 0.12154583]
 [0.99562822 0.         0.        ]
 [0.17494576 0.         0.        ]
 [0.         0.02091257 0.17956197]
 [0.         0.         0.09566999]
 [0.         0.         0.19790097]]


-102.65322056610917

In [ ]:
l = 20000
def normalize(n,p,arr):
    arr2 = arr.reshape((n,p))
    for i in range(n):
        arr2[i] = (arr2[i])/(sum(arr2[i]))
    return arr2.reshape((n*p,))
listSobol = sobol_seq.i4_sobol_generate(n*p, 20000)
sol = 0
for i in range(l):
    te = (posterior(n,p,k,a,b,normalize(n,p,listSobol[i]),rho))
    if te < sol:
        sol = te
print(sol)